apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tech-challenge
  template:
    metadata:
      labels:
        app: tech-challenge
    spec:
      containers:
      - name: tech-challenge-container
        image: tech-challenge:latest
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        envFrom:
        - configMapRef:
            name: tech-challenge-secret
        livenessProbe:
          httpGet:
            path: /api-docs
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api-docs
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
