apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-service
spec:
  type: NodePort
  selector:
    app: tech-challenge
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000
